### PR TITLE
Manage agent pools and project association

### PR DESCRIPTION
**Pull request by GennadySpb**
Continue work done by @tombuildsstuff at #79

### CODE REVIEW

**Comment by GennadySpb** [comment]
I want to note that the code (and the adapted version of the provider: terraform-provider-teamcity with [PR](https://github.com/cvbarros/terraform-provider-teamcity/pull/80)) is already used to manage pools and associations.

**Comment by GennadySpb** [comment]
@cvbarros please check this out :)

**Comment by GennadySpb** [comment]
kind up

**Comment by cvbarros** [comment]
Super, @GennadySpb! Thanks a bunch for taking this forward. Will merge and shortly release with `1.3.0`.

**Comment by GennadySpb** [comment]
Hey @cvbarros ! 
What about to make release of `go-teamcity` ? It's already has [bunch of nice changes](https://github.com/cvbarros/go-teamcity/milestone/4?closed=1).

The release is also useful for a [pull request](https://github.com/cvbarros/terraform-provider-teamcity/pull/107).

**Pull request merged**
