### PR TITLE
Add Octopus Create Release support

### PR DESCRIPTION
**Pull request by ss-remygreinhofer**
This patch implements the support for Octopus
(https://octopus.com/docs/api-and-integration/teamcity). It allows to
define a new type of build step: "octopus.create.release".

### CODE REVIEW

**Comment by ss-remygreinhofer** [comment]
I'll rebase, add the tests and all the good stuff soon.

**Comment by gertjvr** [comment]
Any change this can get merged soon?

**Comment by cvbarros** [comment]
@ss-remygreinhofer @gertjvr Thanks for this! I'll review this next week. Been busy the past few months, but I'll retake active maintenance on the project. Cheers!

**Comment by cvbarros** [comment]
@ss-remygreinhofer as #64 merged, this causes conflict with import path for the package causing CI to tail. Would you mind rebasing to latest master so we can merge this?
Thanks!

**Comment by ss-remygreinhofer** [comment]
Updated!

**Pull request merged**
